slug: fenix_122_vs_fenix_129
histograms: []
branches:
- name: Fenix122
  startDate: '2024-01-23'
  endDate: '2024-02-20'
  channel: release
  version: 122
  conditions: []
- name: Fenix129
  startDate: '2024-08-06'
  endDate: '2024-09-03'
  channel: release
  version: 129
  conditions: []
segments:
- Android
events:
- pageload:
    dns_lookup_time:
      max: 30000
    response_time:
      max: 30000
    fcp_time:
      max: 30000
    lcp_time:
      max: 30000
    load_time:
      max: 30000
