slug: fetchpriority-beta-followup
histograms: []
segments:
- All
- Windows
- Linux
- Mac
events:
- pageload:
    fcp_time:
      max: 30000
    lcp_time:
      max: 30000
    load_time:
      max: 30000
