slug: firefox_112_vs_firefox_122
histograms:
- payload.processes.content.histograms.perf_page_load_time_ms
- payload.processes.content.histograms.perf_page_load_time_from_responsestart_ms
- payload.processes.content.histograms.perf_first_contentful_paint_ms
- payload.processes.content.histograms.perf_first_contentful_paint_from_responsestart_ms
- payload.processes.content.histograms.time_to_response_start_ms
- payload.processes.content.histograms.input_event_response_ms
- payload.processes.content.histograms.cycle_collector_max_pause
- payload.processes.content.histograms.gc_max_pause_ms_2
- payload.processes.content.histograms.gc_ms
- payload.processes.content.histograms.js_pageload_execution_ms
- payload.processes.content.histograms.js_pageload_parse_ms
- payload.processes.content.histograms.js_pageload_baseline_compile_ms
- payload.histograms.fx_new_window_ms
- payload.histograms.fx_tab_switch_composite_e10s_ms
- payload.histograms.memory_total
branches:
- name: Firefox112
  startDate: '2023-04-11'
  endDate: '2023-05-09'
  channel: release
  version: 112
  conditions: []
- name: Firefox122
  startDate: '2024-01-23'
  endDate: '2024-02-11'
  channel: release
  version: 122
  conditions: []
pageload_event_metrics:
  fcp_time:
    max: 3000
  load_time:
    max: 10000
  response_time:
    max: 3000
  js_exec_time:
    max: 3000
segments:
- All
- Windows
- Linux
- Mac
