slug: impact-of-nursery-size
control: control
histograms:
- payload.processes.content.histograms.perf_page_load_time_ms
- payload.processes.content.histograms.time_to_first_interaction_ms
- payload.processes.content.histograms.perf_first_contentful_paint_ms
- payload.processes.content.histograms.js_pageload_execution_ms
- payload.histograms.memory_total
- payload.processes.content.histograms.input_event_response_ms
- payload.processes.content.histograms.cycle_collector_max_pause
- payload.processes.content.histograms.gc_max_pause_ms_2
- payload.processes.content.histograms.gc_ms
- payload.processes.content.histograms.gc_minor_us
- payload.processes.content.histograms.gc_nursery_bytes_2
- payload.processes.content.histograms.gc_minor_reason
- payload.processes.content.histograms.gc_minor_reason_long
- payload.processes.content.histograms.gc_mark_ms
- payload.processes.content.histograms.gc_mark_rate_2
- payload.processes.content.histograms.gc_sweep_ms
- payload.processes.content.histograms.gc_slice_count
- payload.processes.content.histograms.gc_slice_was_long
- payload.processes.content.histograms.gc_budget_overrun
- payload.processes.content.histograms.gc_budget_was_increased
pageload_event_metrics:
  fcp_time:
    max: 120000
  lcp_time:
    max: 120000
  load_time:
    max: 120000
  response_time:
    max: 120000
  js_exec_time:
    max: 30000
segments:
  Windows: []
  Linux: []
  Mac: []
