slug: impact-of-parallel-marking-on-android
histograms:
- metrics.timing_distribution.performance_pageload_fcp
- metrics.timing_distribution.perf_largest_contentful_paint
- metrics.timing_distribution.javascript_gc_mark_time
- metrics.timing_distribution.javascript_gc_minor_time
- metrics.timing_distribution.javascript_gc_prepare_time
- metrics.timing_distribution.javascript_gc_slice_time
- metrics.timing_distribution.javascript_gc_sweep_time
- metrics.timing_distribution.javascript_gc_total_time
- metrics.timing_distribution.javascript_gc_compact_time
- metrics.timing_distribution.javascript_gc_mark_roots_time
segments:
- Android
events:
- pageload:
    fcp_time:
      max: 30000
    load_time:
      max: 30000
    response_time:
      max: 30000
    js_exec_time:
      max: 30000
